spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trocme
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 5001